<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>read_write_suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>35</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e43b1120-8d0a-478d-87de-293f5e2bc7ea</testSuiteGuid>
   <testCaseLink>
      <guid>bca18c98-1fd2-46fb-8e2c-bce4498af407</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/drag_and_drop_file_upload</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dc3fba99-4791-4a4b-a6f5-8d7d4c75e9b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/read_write_data</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1f8874f6-2bd7-4222-bae6-aaf89c3c6f24</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginDetails/batchfile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>1f8874f6-2bd7-4222-bae6-aaf89c3c6f24</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>id</value>
         <variableId>6407f220-8292-40c1-9ac8-baffac335501</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1f8874f6-2bd7-4222-bae6-aaf89c3c6f24</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>9cb09735-1a71-4ddc-9e70-bc0160c8ce14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1f8874f6-2bd7-4222-bae6-aaf89c3c6f24</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5f16ba89-eb8a-48af-8269-64bf9345b066</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
