<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_file</name>
   <tag></tag>
   <elementGuidId>db0c8462-8b6a-4d47-9281-05cc86543d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;content-library-list&quot;]//tr/td[@class='col-name']/span[text()='${file_name}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;content-library-list&quot;]//tr/td[@class='col-name']/span[text()='${file_name}']</value>
   </webElementProperties>
</WebElementEntity>
