<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Homepage_Logo</name>
   <tag></tag>
   <elementGuidId>11e1906f-2401-40d4-9c24-a561854ed882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>a[class=&quot;logo-holder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>a[class=&quot;logo-holder&quot;]</value>
   </webElementProperties>
</WebElementEntity>
