<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shop_by_category_submenu_selection</name>
   <tag></tag>
   <elementGuidId>81e38564-73f1-4ad2-91c9-aa72dfa170fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'shop_by_category_section')]//ul/li/a[text()='${selection}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'shop_by_category_section')]//ul/li/a[text()='${selection}']</value>
   </webElementProperties>
</WebElementEntity>
