<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Cancel_contentLibrary</name>
   <tag></tag>
   <elementGuidId>ebc0eedd-c788-491f-a1ed-4d2b5d52a8ca</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contentLibrary</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'contentLibrary' and @name = 'contentLibrary' and @src = 'https://contentlibrary.benefithub.info?EncQS=RQBBAEEAQQBBAE0AQQBpAEQAMgBaAHcAUQBFAHgAegBwAFMALwBYAFUAWABCAEcAWQAzAHUANwB5AGsAYgBjAFMATABjAGoAUgB0AGEAWgBFAEwATQBIAGoAeQA2AEUAMABzAEUAZgB3AFMAaABvACsAWABEAEIAeABOAFoAdgBwAEIATQBaAGwANAAxADMAWABnAHIAUABtAEcAVAArAEoAcABxAHkAVABqACsAZwB4AEwAcABzAGUAdgB3AFUAVgBJAHgALwAyAEoASgA5AFAAQQBqAHoAYgBqADgAeABSAEkAVgB5AFYALwBQADQAWgBkAHYAYgBDAHoAZgA5AHAAMwBRAGkAUQB4ADUAMABHAGcARgBlADUAMABiAEEAQgBYAFYARwBPAGcAWQAzADIAbwBPADUAOQBNAGUAaABpADEATgB6AE8AQQBhAG4ATQBkAGwAcgBHADEAVgBiAA==']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='contentLibrary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentLibrary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentLibrary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://contentlibrary.benefithub.info?EncQS=RQBBAEEAQQBBAE0AQQBpAEQAMgBaAHcAUQBFAHgAegBwAFMALwBYAFUAWABCAEcAWQAzAHUANwB5AGsAYgBjAFMATABjAGoAUgB0AGEAWgBFAEwATQBIAGoAeQA2AEUAMABzAEUAZgB3AFMAaABvACsAWABEAEIAeABOAFoAdgBwAEIATQBaAGwANAAxADMAWABnAHIAUABtAEcAVAArAEoAcABxAHkAVABqACsAZwB4AEwAcABzAGUAdgB3AFUAVgBJAHgALwAyAEoASgA5AFAAQQBqAHoAYgBqADgAeABSAEkAVgB5AFYALwBQADQAWgBkAHYAYgBDAHoAZgA5AHAAMwBRAGkAUQB4ADUAMABHAGcARgBlADUAMABiAEEAQgBYAFYARwBPAGcAWQAzADIAbwBPADUAOQBNAGUAaABpADEATgB6AE8AQQBhAG4ATQBkAGwAcgBHADEAVgBiAA==</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentLibrary&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='contentLibrary']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
